[package]
name = "easy-games/chickynoid"
description = "A server-authoritative networking character controller for Roblox"
license = "MIT"
authors = ["MrChickenRocket"]
version = "0.1.4"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["types", "example", "docs", "LICENSE", ".**", "**.json", "**.toml", "**.md", "**.lock"]
include = ["default.project.json", "wally.toml"]

[dependencies]
